// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTJdddkzaQQHBoYaMRmejB_4_Oo35fAm4',
    appId: '1:488746501073:web:5ecb04461dffdcc32656f0',
    messagingSenderId: '488746501073',
    projectId: 'fir-food-app-ab2a5',
    authDomain: 'fir-food-app-ab2a5.firebaseapp.com',
    storageBucket: 'fir-food-app-ab2a5.appspot.com',
    measurementId: 'G-6XBF4S63YR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6GQRRaVqjFXUcyDAUK4nrsmZnsTrYnDY',
    appId: '1:488746501073:android:bd00ed5711bb3ad92656f0',
    messagingSenderId: '488746501073',
    projectId: 'fir-food-app-ab2a5',
    storageBucket: 'fir-food-app-ab2a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDGH59Jx4Qntex9907znzw2dciGkRc9uk',
    appId: '1:488746501073:ios:8a63f2b06af79dda2656f0',
    messagingSenderId: '488746501073',
    projectId: 'fir-food-app-ab2a5',
    storageBucket: 'fir-food-app-ab2a5.appspot.com',
    iosBundleId: 'com.example.firebaseFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDGH59Jx4Qntex9907znzw2dciGkRc9uk',
    appId: '1:488746501073:ios:ddf8516833245faa2656f0',
    messagingSenderId: '488746501073',
    projectId: 'fir-food-app-ab2a5',
    storageBucket: 'fir-food-app-ab2a5.appspot.com',
    iosBundleId: 'com.example.firebaseFoodApp.RunnerTests',
  );
}
